[package]
name = "quicktex-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
bitvec = "1.0.1"
itertools = "0.11.0"
vector-victor = "0.1.0"
