name: Test and Deploy
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Run Checks
        run: cargo check

      - name: Run Tests
        run: cargo test


  deploy:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Yaclog
        run: pip install yaclog~=1.1

      - name: Publish to Crates.io
        run: |
          cargo publish \
            --token ${{ secrets.CARGO_TOKEN }} \
            ${{ github.ref_type != 'tag' && '--dry-run' || '' }}

      - name: Publish to Github
        run: |
          gh release create ${{ github.ref_name }} \
            --notes "$(yaclog show -mb)" \
            --title "Version $(yaclog show -n)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
