name: Build and Release
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Yaclog
        run: pip install yaclog~=1.1

      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal --component rustfmt

      - name: Install NVTT
        run: sudo apt install libnvtt-bin

      - name: Run Checks
        run: cargo check

      - name: Run Tests
        run: cargo test

      - name: Publish to Crates.io
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          cargo publish \
            --token ${{ secrets.CARGO_TOKEN }} \
            ${{ github.ref_type != 'tag' && '--dry-run' || '' }}

      - name: Publish to Github
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          gh release create ${{ github.ref_name }} \
            --notes "$(yaclog show -mb)" \
            --title "Version $(yaclog show -n)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
